"""Add column media

Revision ID: 09d7e7a956dc
Revises: 8f97b49c304e
Create Date: 2022-11-20 00:58:44.590824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d7e7a956dc'
down_revision = '8f97b49c304e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('media', sa.String(), nullable=True))
    # ### end Alembic commands ###


